export const ChatType = [
    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',
    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
    'Eva Elfie[PRO]',
    'Psychologist',
    'English Tutor',    'Assistant',
    'Brief Assistant',
    'Code Developer',
    'DALLE3 - Image Generation [PRO]',
];